google.maps.__gjsload__('geometry', function(_){var ev=function(a,b){return Math.abs(_.de(b-a,-180,180))},fv=function(a,b,c,d,e){if(!d){c=ev(a.lng(),c)/ev(a.lng(),b.lng());if(!e)return e=Math.sin(_.Jc(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Jc(b.lat())),_.Kc(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.O(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Jc(a.lat());a=_.Jc(a.lng());d=_.Jc(b.lat());b=_.Jc(b.lng());c=_.Jc(c);return _.de(_.Kc(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},gv=_.n(),hv={containsLocation:function(a,b){var c=_.de(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var r=l.getAt(m),u=l.getAt((m+1)%q),v=_.de(r.lng(),-180,180),x=_.de(u.lng(),-180,180),w=Math.max(v,x);v=Math.min(v,x);(180<w-v?c>=w||c<v:
c<w&&c>=v)&&fv(r,u,c,d,f)<a.lat()&&(g=!g)}return g||hv.isLocationOnEdge(a,b)}};_.Va("PolyGeometry.containsLocation",hv.containsLocation);
hv.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.de(a.lng(),-180,180),e=b instanceof _.oj,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,r=0;r<q;++r){var u=l.getAt(r),v=l.getAt((r+1)%m),x=_.de(u.lng(),-180,180),w=_.de(v.lng(),-180,180),E=Math.max(x,w),J=Math.min(x,w);if(x=1E-9>=Math.abs(_.de(x-w,-180,180))&&(Math.abs(_.de(x-d,-180,180))<=c||Math.abs(_.de(w-d,-180,180))<=
c)){x=a.lat();w=Math.min(u.lat(),v.lat())-c;var N=Math.max(u.lat(),v.lat())+c;x=x>=w&&x<=N}if(x)return!0;if(180<E-J?d+c>=E||d-c<=J:d+c>=J&&d-c<=E)if(u=fv(u,v,d,f,b),Math.abs(u-a.lat())<c)return!0}return!1};_.Va("PolyGeometry.isLocationOnEdge",hv.isLocationOnEdge);var iv={computeHeading:function(a,b){var c=_.Ee(a),d=_.Fe(a);a=_.Ee(b);b=_.Fe(b)-d;return _.de(_.Kc(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Va("Spherical.computeHeading",iv.computeHeading);
iv.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.Jc(c);var e=_.Ee(a);a=_.Fe(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.I(_.Kc(Math.asin(g)),_.Kc(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Va("Spherical.computeOffset",iv.computeOffset);
iv.computeOffsetOrigin=function(a,b,c,d){c=_.Jc(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Ee(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Fe(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.I(_.Kc(g),_.Kc(a))};
_.Va("Spherical.computeOffsetOrigin",iv.computeOffsetOrigin);iv.interpolate=function(a,b,c){var d=_.Ee(a),e=_.Fe(a),f=_.Ee(b),g=_.Fe(b),h=Math.cos(d),k=Math.cos(f);b=iv.mg(a,b);var l=Math.sin(b);if(1E-6>l)return new _.I(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.I(_.Kc(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Kc(Math.atan2(e,b)))};_.Va("Spherical.interpolate",iv.interpolate);
iv.mg=function(a,b){var c=_.Ee(a);a=_.Fe(a);var d=_.Ee(b);b=_.Fe(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};iv.computeDistanceBetween=function(a,b,c){c=c||6378137;return iv.mg(a,b)*c};_.Va("Spherical.computeDistanceBetween",iv.computeDistanceBetween);iv.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.og&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=iv.computeDistanceBetween(a[d],a[d+1],b);return c};
_.Va("Spherical.computeLength",iv.computeLength);iv.computeArea=function(a,b){return Math.abs(iv.computeSignedArea(a,b))};_.Va("Spherical.computeArea",iv.computeArea);iv.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.og&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=iv.zk(c,a[e],a[e+1]);return d*b*b};_.Va("Spherical.computeSignedArea",iv.computeSignedArea);iv.zk=function(a,b,c){return iv.Ak(a,b,c)*iv.Al(a,b,c)};
iv.Ak=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=iv.mg(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
iv.Al=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.Ee(d);d=_.Fe(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var jv={decodePath:function(a){for(var b=_.Zd(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.I(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Va("PolylineCodec.decodePath",jv.decodePath);
jv.encodePath=function(a){a instanceof _.og&&(a=a.getArray());return jv.un(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Va("PolylineCodec.encodePath",jv.encodePath);jv.un=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.Zd(a);f<g;++f)e=b?b(a[f]):a[f],jv.dj(e[0]-d[0],c),jv.dj(e[1]-d[1],c),d=e;return c.join("")};jv.dj=function(a,b){jv.vn(0>a?~(a<<1):a<<1,b)};jv.vn=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.z.google.maps.geometry={encoding:jv,spherical:iv,poly:hv};_.t=gv.prototype;_.t.decodePath=jv.decodePath;_.t.encodePath=jv.encodePath;_.t.computeDistanceBetween=iv.computeDistanceBetween;_.t.interpolate=iv.interpolate;_.t.computeHeading=iv.computeHeading;_.t.computeOffset=iv.computeOffset;_.t.computeOffsetOrigin=iv.computeOffsetOrigin;_.ff("geometry",new gv);});
